// <auto-generated />
using CqrsApiExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CqrsApiExample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250827003934_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CqrsApiExample.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "High performance laptop",
                            Name = "Laptop",
                            Price = 1200.50m
                        },
                        new
                        {
                            ID = 2,
                            Description = "Latest Android smartphone",
                            Name = "Smartphone",
                            Price = 800.00m
                        },
                        new
                        {
                            ID = 3,
                            Description = "Noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            ID = 4,
                            Description = "27-inch 4K monitor",
                            Name = "Monitor",
                            Price = 350.75m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
